version: 2

project_name: sitepanda
before:
  hooks:
  - go mod tidy
  - go build -o sitepanda .
  - pwd
  - ls -la
  - mkdir -p completions
  - ls -la completions/ || echo "completions directory not found"
  - ./sitepanda --version
  - bash -c './sitepanda completion bash > completions/sitepanda.bash' || echo "bash completion failed"
  - bash -c './sitepanda completion zsh > completions/_sitepanda' || echo "zsh completion failed"  
  - bash -c './sitepanda completion fish > completions/sitepanda.fish' || echo "fish completion failed"
  - ls -la completions/
  - find . -name "*.bash" -o -name "*sitepanda*" | head -10

builds:
  - id: sitepanda
    binary: sitepanda
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - darwin_arm64
      - windows_amd64

archives:
  - formats: [tar.gz]
    ids: [sitepanda]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "completions/*"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

brews:
  - repository:
      owner: hokupod
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    install: |
      bin.install "sitepanda"
      bash_completion.install "completions/sitepanda.bash" => "sitepanda"
      zsh_completion.install "completions/_sitepanda" => "_sitepanda"
      fish_completion.install "completions/sitepanda.fish"
